// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mflaeihhyptgauqxiwfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mbGFlaWhoeXB0Z2F1cXhpd2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzU1NjEsImV4cCI6MjA1NzcxMTU2MX0.-WVAMPglPEH-jVagOBn4RJpNSYvnYLLW8W9UNyD5ivs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);